---
- name: "[Install] Install required packages"
  ansible.builtin.package:
    name: "{{ package }}"
  loop: "{{ packages }}"
  loop_control:
    loop_var: package
  tags:
    - install

- name: "[Install] Create the {{ opensearch_group }} group"
  ansible.builtin.group:
    name: "{{ opensearch_group }}"
    state: present
    system: true
  tags:
    - install

- name: "[Install] Create the {{ opensearch_user }} user"
  ansible.builtin.user:
    name: "{{ opensearch_user }}"
    groups: "{{ opensearch_group }}"
    append: true
    shell: /bin/bash
    system: true
    create_home: false
  tags:
    - install

- name: "[Install] Check if versions already exists"
  ansible.builtin.stat: 
    path: "{{ opensearch_path }}-{{ opensearch_version }}"
  register: installed_path
  tags:
    - install

- name: "[Install] Download Binary"
  ansible.builtin.get_url:
    url: "{{ opensearch_package_url }}"
    dest: "/tmp/opensearch-{{ opensearch_version }}-linux-x64.tar.gz"
    mode: '0644'
  register: download_binary
  until: download_binary is succeeded
  retries: 12
  delay: 5
  when: not installed_path.stat.exists 
  tags:
    - install

- name: "[Install] Unpack binary"
  ansible.builtin.unarchive:
    src: "/tmp/opensearch-{{ opensearch_version }}-linux-x64.tar.gz"
    dest: "{{ opensearch_install_path }}"
    owner: "{{ opensearch_user }}"
    group: "{{ opensearch_group }}"
    remote_src: yes
  when: not installed_path.stat.exists
  tags:
    - install

- name: "[Install] Remove tarfile"
  ansible.builtin.file:
    path: "/tmp/opensearch-{{ opensearch_version }}-linux-x64.tar.gz"
    state: absent
  tags:
    - install

- name: "[Install] Create path link"
  ansible.builtin.file:
    src: "{{ opensearch_path }}-{{ opensearch_version }}"
    dest: "{{ opensearch_path }}"
    owner: "{{ opensearch_user }}"
    group: "{{ opensearch_group }}"
    state: link
  tags:
    - install

- name: "[Install] Get installed Plugins"
  ansible.builtin.shell: "{{ opensearch_plugin_bin_file }} list"
  register: installed_plugins
  changed_when: false
  tags:
    - install

- name: "[Install] Install Plugins"
  ansible.builtin.shell: "{{ opensearch_plugin_bin_file }} install -b {{ item }}"
  when: item not in installed_plugins.stdout_lines
  with_items: "{{ opensearch_plugins }}"
  tags:
    - install

- name: "[Install] Get config path"
  ansible.builtin.stat: 
    path: "{{ opensearch_config_path }}"
  register: config_path
  tags:
    - install

- name: "[Install] Move config to {{ opensearch_config_path }}"
  ansible.builtin.command: mv "{{ opensearch_path }}/config" "{{ opensearch_config_path }}"
  when: not config_path.stat.exists
  tags:
    - install

- name: "[Install] Create profile.d"
  ansible.builtin.copy:
    dest: /etc/profile.d/opensearch.sh
    content: |
      export OPENSEARCH_HOME={{ opensearch_path }}
      export OPENSEARCH_PATH_CONF={{ opensearch_config_path }}
    owner: "{{ opensearch_user }}"
    group: "{{ opensearch_group }}"
    mode: "0740"
  tags:
    - install

- name: "[Install] Create log path"
  ansible.builtin.file:
    path: "{{ path_logs }}"
    owner: "{{ opensearch_user }}"
    group: "{{ opensearch_group }}"
    state: directory
    mode: '0740'
  tags:
    - install

- name: "[Install] Create data path"
  ansible.builtin.file:
    path: "{{ path_data }}"
    owner: "{{ opensearch_user }}"
    group: "{{ opensearch_group }}"
    state: directory
    mode: '02750'
  tags:
    - install

- name: "[Install] Create batch_metrics data path"
  ansible.builtin.file:
    path: "{{ opensearch_path }}/data"
    owner: "{{ opensearch_user }}"
    group: "{{ opensearch_group }}"
    state: directory
    mode: '0740'
  tags:
    - install

- name: "[Install] Create tmp path"
  ansible.builtin.file:
    path: "{{ opensearch_path }}/tmp"
    owner: "{{ opensearch_user }}"
    group: "{{ opensearch_group }}"
    state: directory
    mode: '0740'
  tags:
    - install

- name: "[Install] Create pid path"
  ansible.builtin.file:
    path: "{{ opensearch_pid_dir }}"
    owner: "{{ opensearch_user }}"
    group: "{{ opensearch_group }}"
    state: directory
    mode: '0740'
  changed_when: false
  tags:
    - install

- name: "[Install] Create SSL Path"
  ansible.builtin.file:
    path: "{{ ssl_path }}"
    state: directory
    owner: "{{ opensearch_user }}"
    group: "{{ opensearch_group }}"
    mode: "0740"