---
- name: Daemon Reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable service
  ansible.builtin.systemd:
    name: "{{ opensearch_service_name }}"
    enabled: yes

- name: Start service
  ansible.builtin.systemd:
    name: "{{ opensearch_service_name }}"
    state: started

- name: Stop service
  ansible.builtin.systemd:
    name: "{{ opensearch_service_name }}"
    state: stopped

- name: Restart service
  ansible.builtin.systemd:
    name: "{{ opensearch_service_name }}"
    state: restarted
