---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: opensearch-master-0
    image: "${MOLECULE_IMAGE:-yuriclopes/debian-molecule-test:11-slim}"
    command: "${IMAGE_COMMAND:-/sbin/init}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - opensearch
      - opensearch_master
  - name: opensearch-master-1
    image: "${MOLECULE_IMAGE:-yuriclopes/debian-molecule-test:11-slim}"
    command: "${IMAGE_COMMAND:-/sbin/init}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - opensearch
      - opensearch_master
  - name: opensearch-data-0
    image: "${MOLECULE_IMAGE:-yuriclopes/debian-molecule-test:11-slim}"
    command: "${IMAGE_COMMAND:-/sbin/init}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - opensearch
      - opensearch_data
  - name: opensearch-data-1
    image: "${MOLECULE_IMAGE:-yuriclopes/debian-molecule-test:11-slim}"
    command: "${IMAGE_COMMAND:-/sbin/init}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - opensearch
      - opensearch_data
provisioner:
  name: ansible
  inventory:
    host_vars:
      opensearch-master-0:
        node_address: opensearch-master-0
      opensearch-master-1:
        node_address: opensearch-master-1
      opensearch-data-0:
        node_address: opensearch-data-0
      opensearch-data-1:
        node_address: opensearch-data-1
    group_vars:
      opensearch:
        ansible_user: ansible
        ssl_clients:
          - cert_name: molecule-1
            days: 7
          - cert_name: molecule-2
            days: 7
        is_bootstrapping: true
verifier:
  name: ansible
