---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: "Load all defaults files"
      ansible.builtin.include_vars:
        file: "../../vars/main.yml"

    - name: "Load all defaults files"
      ansible.builtin.include_vars:
        dir: "../../defaults/"

    - name: Get OpenSearch Cluster status
      environment:
        SSL_CERT_FILE: "{{ ssl_path }}/{{ ssl_root_ca_cert_name }}"
      ansible.builtin.uri:
        url: "https://{{ node_address }}:{{ http_port }}/_cluster/stats?pretty"
        url_username: admin
        url_password: admin
        client_cert: "{{ ssl_path }}/admin.pem"
        client_key: "{{ ssl_path }}/admin-key.pem"
        force_basic_auth: yes
      register: status_query
      become: yes
      when: ansible_master_group in group_names

    - name: Assert that cluster is Green with all members
      ansible.builtin.assert:
        that:
          - status_query.json.status == 'green'
          - status_query.json.nodes.count.data == 2
          - status_query.json.nodes.count.master == 2
          - status_query.json.nodes.count.total == 4
          - status_query.json.nodes.count.ingest == 4
      when: ansible_master_group in group_names